name: Scheduled Job

on:
  schedule:
    - cron: "0,41 * * * *"  # runs every 30 minutes (00 and 30 minutes past each hour)
  workflow_dispatch:         # optional: manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run script
        run: |
          python src/main.py
