name: Scheduled Job

on:
  schedule:
    - cron: "0 2 * * *"   # runs at 02:00 UTC = 07:30 IST every day
    - cron: "30 6 * * *"   # 12:00 IST
  workflow_dispatch:       # optional: allows manual run

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run script
        run: |
          python src/main.py
