name: Run on Form Submission

on:
  repository_dispatch:
    types: [form_submitted]

jobs:
  run-script:
      runs-on: ubuntu-latest
      env:
        # 🔐 Secrets (private, safe for credentials & API keys)
        UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
        IMAGE_URL: ${{ secrets.IMAGE_URL }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        TEMP_RECIEVER: ${{ secrets.TEMP_RECIEVER }}
        REDDIT_API_SECRET: ${{ secrets.REDDIT_API_SECRET }}
        REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
        REDDIT_USER: ${{ secrets.REDDIT_USER }}
        REDDIT_PASS: ${{ secrets.REDDIT_PASS }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        SERVICE_ACC_KEY: ${{ secrets.SERVICE_ACC_KEY }}
        UNSUBSCRIBE_SHEET_ID: ${{ secrets.UNSUBSCRIBE_SHEET_ID }}

      steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.11"

        - name: Install dependencies
          run: |
            pip install -r requirements.txt || pip install requests python-dotenv pillow numpy

        - name: Debug secrets
          run: |
            echo "EMAIL_USER: ${{ secrets.EMAIL_USER }}"
            echo "EMAIL_PASS: ${{ secrets.EMAIL_PASS }}"
            echo "UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}"
            echo "TEMP_RECIEVER: ${{ secrets.TEMP_RECIEVER }}"

        - name: Run script
          run: |
            python src/main.py "${{ github.event.client_payload['Email ID'] }}"