name: Scheduled Email Job

on:
  schedule:
    - cron: "0 2 * * *"   # 07:30 AM IST (02:00 UTC)
    - cron: "30 6 * * *"   # 12:00 PM IST 
  workflow_dispatch:       # allows manual trigger from Actions tab

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      # 🔐 Secrets (private, safe for credentials & API keys)
      UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
      IMAGE_URL: ${{ secrets.IMAGE_URL }}
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      TEMP_RECIEVER: ${{ secrets.TEMP_RECIEVER }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || pip install requests python-dotenv pillow numpy

      - name: Debug secrets
        run: |
          echo "EMAIL_USER: ${{ secrets.EMAIL_USER }}"
          echo "EMAIL_PASS: ${{ secrets.EMAIL_PASS }}"
          echo "UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}"
          echo "TEMP_RECIEVER: ${{ secrets.TEMP_RECIEVER }}"

      - name: Run script
        run: python src/main.py
