name: Run on unsoobscribe

on:
  repository_dispatch:
    types: [unsubscribed]

jobs:
  run-script:
      runs-on: ubuntu-latest
      env:
        # 🔐 Secrets (private, safe for credentials & API keys)
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        SERVICE_ACC_KEY: ${{ secrets.SERVICE_ACC_KEY }}

      steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.11"

        - name: Install dependencies
          run: |
            pip install -r requirements.txt || pip install requests python-dotenv pillow numpy

        - name: Debug secrets
          run: |
            echo "EMAIL_USER: ${{ secrets.EMAIL_USER }}"
            echo "EMAIL_PASS: ${{ secrets.EMAIL_PASS }}"
            echo "UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}"
            echo "TEMP_RECIEVER: ${{ secrets.TEMP_RECIEVER }}"

        - name: Run script
          run: |
            python src/unsoobscribe.py "${{ github.event.client_payload['Email Address'] }}"